


abb_dict = {
    
    "approx.": "approximately",
    "appt." : "appointment",
    "a.s.a.p.": "as soon as possible",
#     "asap": "as soon as possible",
    "b.y.o.b." : "bring your own bottle, used for parties where guests are expected to bring their own drinks or restaurants\
                  that don't sell alcohol.",
    "c/o" : "care of",
    "dept.": "department",
    "d.i.y." : "Do it yourself",
    "est.": "established",
    "e.t.a." : "estimated time of arrival",
    "min" : "minimum",
    "misc." : "miscellaneous",
    "mr" : 'Mister',    
    "mrs" : "Missus",
    "no."  : "number",
    "a/c" : "account",
    "dr"  : "Doctor",
    "i.e." : "that is",
    "st": "saint",
    "co": "company",
    "jr": "junior" ,
    "maj": "major",
    "gen": "general",
    "drs": "doctors",
    "rev": "reverend",
    "lt": "lieutenant",
    "hon": "honorable",
    "capt": "captain",
    "sgt": "sergeant",
    "esq": "esquire",
    "ltd": "limited",
    "col": "colonel",
    "ft": "fort",
    "mm" : "milimeter",
    "eng": "engineering",
    "cbp": "C B P",
    "uk" : "United Kingdom",
    "uk.": "United Kingdom",
    "usa" : "United States of America",
    "uae" : "United Arab  emirates",
    "usa." : "United States of America",
    "uae." : "United Arab  emirates",
    "uk,": "United Kingdom",
    "usa," : "United States of America",
    "uae," : "United Arab  emirates",
    "u": "eu",
    "k" : "kae",
    "b" : "be",
    "s" : "as",
    "m" : "am",
    "c" : "si",
#     "d" : "de",
    
    
    
}
